### ISSUE TITLE
"Faults, Provisions and Virtual Parameters" tabs do not work.

### ISSUE THREAD

**Issue by djxoxe** [zaidka/genieacs-gui#58]
I have GenieACS installed and it works well: I have several CPEs registered in the ACS.

My problem is that the Faults, Provisions and Virtual Parameters tabs do not work, the error message shown in this screenshot appears below.

Can anyone help me figure out why this happens?

Greetings.

![error tabs genieacs](https://cloud.githubusercontent.com/assets/25243945/22203487/a0cfa33c-e16d-11e6-98f1-596e1605105f.jpg)

**Comment by akcoder** [comment]
What is in the logs for the GUI?

**Comment by djxoxe** [comment]
In what file can i see the logs for the GUI, Akcoder ?

**Comment by akcoder** [comment]
That entirely depends on how you are the GUI running. If you are using
Passenger, then you would check the apache logs. If you are using the
built-in ruby web server (which you should not be doing), then you would
run it in a console window.

**Comment by djxoxe** [comment]
My GUI running in a docker container.

**Comment by akcoder** [comment]
Sounds to me like you need to figure out how to get the logs then.

**Comment by djxoxe** [comment]
I see the logs in /var/log but not show anything. ¿Where is this logs files?

**Comment by akcoder** [comment]
Again, thats on you to figure out. You might want to consult who ever setup
the docker container. You need to figure out how the GUI is running. Once
you have that information, you should be able to figure out where the log
file is (if anything is being logged).
-dan

**Comment by djxoxe** [comment]
Thank you very much for your answers. They are of great help.

**Comment by DrumSergio** [comment]
Better to talk about this in the mailing list http://lists.genieacs.com/mailman/listinfo , @djxoxe 

Thank you!

**Comment by davidcodesido** [comment]
I'm having the same issue as djxoxe in a fresh installation but I could find the logs ;)

App 23671 stderr: Started GET "/faults" for 213.60.51.210 at 2017-02-08 12:46:01 +0100
App 23671 stderr: Cannot render console from 213.60.51.210! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
App 23671 stderr: Processing by FaultsController#index as HTML
App 23671 stderr: Completed 500 Internal Server Error in 24ms (ActiveRecord: 0.0ms)
App 23671 stderr:
App 23671 stderr:
App 23671 stderr:
App 23671 stderr: JSON::ParserError (822: unexpected token at 'Not Found'):
App 23671 stderr:
App 23671 stderr: app/controllers/faults_controller.rb:15:in `find_faults'
App 23671 stderr: app/controllers/faults_controller.rb:29:in `block in index'
App 23671 stderr: app/controllers/application_controller.rb:40:in `can?'
App 23671 stderr: app/controllers/faults_controller.rb:21:in `index'
App 23671 stderr:   Rendering /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
App 23671 stderr:   Rendering /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
App 23671 stderr:   Rendered /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (5.8ms)
App 23671 stderr:   Rendering /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
App 23671 stderr:   Rendered /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.5ms)
App 23671 stderr:   Rendering /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
App 23671 stderr:   Rendered /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
App 23671 stderr:   Rendered /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (31.4ms)

└─┬ genieacs@1.0.7
  ├─┬ hiredis@0.4.1
  │ ├── bindings@1.2.1
  │ └── nan@2.5.1
  ├─┬ libxmljs@0.14.3
  │ ├── bindings@1.2.1
  │ └── nan@2.0.7
  ├─┬ mongodb@1.4.40
  │ ├─┬ bson@0.2.22
  │ │ └── nan@1.8.4
  │ ├─┬ kerberos@0.0.11
  │ │ └── nan@1.8.4
  │ └─┬ readable-stream@2.2.2
  │   ├── buffer-shims@1.0.0
  │   ├── core-util-is@1.0.2
  │   ├── inherits@2.0.3
  │   ├── isarray@1.0.0
  │   ├── process-nextick-args@1.0.7
  │   ├── string_decoder@0.10.31
  │   └── util-deprecate@1.0.2
  └── redis@0.12.1

ii  mongodb                              1:2.4.10-5                   amd64        object/document-oriented database (metapackage)
ii  mongodb-clients                      1:2.4.10-5                   amd64        object/document-oriented database (client apps)
ii  mongodb-dev                          1:2.4.10-5                   amd64        object/document-oriented database (development)
ii  mongodb-server                       1:2.4.10-5                   amd64        object/document-oriented database (server package)

ii  redis-server                         2:2.8.17-1+deb8u5            amd64        Persistent key-value database with network interface
ii  redis-tools                          2:2.8.17-1+deb8u5            amd64        Persistent key-value database with network interface (client)

rails -v
Rails 5.0.0

And I'm in the commit: 68cd95e7760a30a8791a8b3c1f7f4a7dfe5e6bee for the GenieACS GUI.

@djxoxe Since you're running a docker, maybe you can try with docker logs. Other option is that you ask the one that built the Dockerfile (assuming that it is someone other than you) where you can find them.

**Comment by davidcodesido** [comment]
I tried with an older commit that I know that was working in a different environment: a424c0e2b58d9ba5910a4e89c65849f39771cb78 and in the same machine it works. Had to run bundle update to adapt the gems and of course it uses an older rails Rails 4.1.16. 

Let me know if I can provide more info.

**Comment by djxoxe** [comment]
@davidcodesido Install the latest version 1.1 and solve the tabs.
