### ISSUE TITLE
_key parameter needs to be enforced to prevent genieacs-cwmp for continuousely fail

### ISSUE THREAD

**Issue by eiselekd** [zaidka/genieacs-gui#72]
Genieacs-gui permits creating a object element with the  "_key" not set.
This will have the effect that genieacs-cwmp will fail continuously when 
trying to access the obj["_keys"] parameter in genieacs/lib/cache.js and 
genieacs/lib/local-cache.js. The Gui should check that _key is set before
adding it to the DB.

**Comment by zaidka** [comment]
This is better fixed in core. If no keys are defined then it should assume all parameters as keys as this was the behavior in v1.0. Just fixed it here zaidka/genieacs@4d255acfc6a0294760e8fb6a6d2c918cd8514f97.

FYI, objects are kept for compatibility only, so you should probably use scripts for all your device configuration.
